"use client";

import { useState } from "react";
import type { NexoCareerInterlude, NexoCareerInterludePlan, NexoCareerStoryChoice } from "../services/nexo-career";

type Person={id:string;name:string;original?:boolean};
type Props={value:NexoCareerInterlude;busy?:boolean;laboratory?:boolean;squad?:Person[];onPlan:(key:string)=>Promise<void>;onStory:(chapter:string,choice:string,configuration:Record<string,unknown>)=>Promise<void>};

export function CareerInterludeProgram({value,busy=false,laboratory=false,squad=[],onPlan,onStory}:Props){
  const [pendingPlan,setPendingPlan]=useState<NexoCareerInterludePlan|null>(null);
  const [pendingChoice,setPendingChoice]=useState<NexoCareerStoryChoice|null>(null);
  const [configuration,setConfiguration]=useState<Record<string,unknown>>({});
  const chapter=value.currentChapter;
  const effectiveInput=pendingChoice?.key==="manager"?"none":pendingChoice?.key==="captains"?"leader":pendingChoice?.input??chapter?.input??"none";
  const day=value.currentDay??value.dayNumber??1;
  const plan=value.planChoices.find((item)=>item.key===value.plan);
  const chosen=new Map(value.storyChoices.map((item)=>[item.chapter,item]));
  const close=()=>{setPendingPlan(null);setPendingChoice(null);setConfiguration({})};
  const configured=!pendingChoice||!chapter||effectiveInput==="none"||(effectiveInput==="players"?Boolean(configuration.mentor&&configuration.youth&&configuration.mentor!==configuration.youth):effectiveInput==="leader"?Boolean(configuration.leader):effectiveInput==="scouting"?Boolean(configuration.position&&configuration.profile):Boolean(configuration[effectiveInput]));
  async function confirm(){if(pendingPlan)await onPlan(pendingPlan.key);else if(pendingChoice&&chapter)await onStory(chapter.key,pendingChoice.key,configuration);close()}
  return <section className="career-story">
    <header className="career-story-hero"><div><p className="eyebrow">INTERLUDIO · J{value.fromMatchday} CERRADA</p><h1>{plan?.title??"Elige la historia de este descanso"}</h1><p>{plan?.summary??"No necesitas entrar cada día. Tomarás unas pocas decisiones importantes que construirán una historia hasta abrir la siguiente jornada."}</p></div><aside><small>SE ABRE LA J{value.toMatchday}</small><strong>{new Date(value.preparationOpensAt??value.endsAt).toLocaleDateString("es-ES",{day:"numeric",month:"short"})}</strong><em>{laboratory?`Día simulado ${day}`:`Calendario real`}</em></aside></header>
    {!value.plan?<div className="career-story-plans">{value.planChoices.map((item)=><button key={item.key} disabled={busy} onClick={()=>setPendingPlan(item)}><i>{item.icon}</i><small>{item.categories.slice(0,2).join(" · ")}</small><strong>{item.title}</strong><p>{item.summary}</p><em>Comenzar esta historia →</em></button>)}</div>:<>
      <nav className="career-story-timeline" aria-label="Capítulos del interludio">{value.story.map((item,index)=>{const decision=chosen.get(item.key);const active=item.key===chapter?.key;return <article className={decision?"done":active?"active":"locked"} key={item.key}><span>{decision?"✓":index+1}</span><p><small>{item.label} · DÍA {item.day}</small><strong>{item.title}</strong></p><em>{decision?decision.title:active?"Decidir ahora":"Se abrirá más adelante"}</em></article>})}</nav>
      {chapter?<section className="career-story-chapter"><header><p className="eyebrow">{chapter.label} · CAPÍTULO {value.story.findIndex((item)=>item.key===chapter.key)+1}</p><h2>{chapter.title}</h2><p>{chapter.description}</p></header><div>{chapter.choices.map((choice)=><button key={choice.key} disabled={busy} onClick={()=>setPendingChoice(choice)}><strong>{choice.title}</strong><p>{choice.summary}</p><span>{choice.consequence}</span><em>Ver consecuencias →</em></button>)}</div></section>:<section className="career-story-wait"><span>✓</span><div><small>CAPÍTULO COMPLETADO</small><h2>{value.storyChoices.length>=value.story.length?"La historia está completa":"Ahora el club sigue trabajando"}</h2><p>{value.storyChoices.length>=value.story.length?`Las consecuencias se aplicarán al abrir la J${value.toMatchday}.`:`El siguiente capítulo se desbloqueará según avance el calendario. No necesitas realizar actividades repetitivas mientras tanto.`}</p></div></section>}
      {!!value.storyChoices.length&&<section className="career-story-diary"><header><p className="eyebrow">HISTORIA DEL DESCANSO</p><h2>Tus decisiones</h2></header>{value.storyChoices.map((item,index)=><article key={`${item.chapter}-${index}`}><span>{index+1}</span><p><small>{item.label}</small><strong>{item.chapterTitle}</strong><em>{item.title}</em></p><b>{signed(item.confidenceChange," confianza")} · {signed(item.reputationChange," reputación")} · {moneyChange(item.budgetChange)}</b></article>)}</section>}
    </>}
    {(pendingPlan||pendingChoice)&&<div className="career-story-modal"><article role="dialog" aria-modal="true"><button className="close" onClick={close}>×</button><p className="eyebrow">{pendingPlan?"HISTORIA PARA TODO EL DESCANSO":"ANTES DE DECIDIR"}</p><h2>{pendingPlan?.title??pendingChoice?.title}</h2><p>{pendingPlan?.summary??pendingChoice?.summary}</p>{pendingPlan?<div className="career-story-explainer"><b>¿Qué ocurrirá?</b><p>Se abrirán cuatro capítulos distintos a medida que pasen los días. Tus decisiones formarán el informe final y no tendrás que completar tareas diarias.</p></div>:pendingChoice&&<><div className="career-story-consequence"><small>CONSECUENCIA</small><strong>{pendingChoice.consequence}</strong><p>{signed(pendingChoice.confidenceChange," confianza")} · {signed(pendingChoice.reputationChange," reputación")} · {moneyChange(pendingChoice.budgetChange)}</p></div>{effectiveInput!=="none"&&<StoryConfiguration input={effectiveInput} squad={squad} value={configuration} onChange={setConfiguration}/>}</>}<footer><button onClick={close}>Volver</button><button disabled={busy||!configured} onClick={()=>void confirm()}>{busy?"Guardando…":pendingPlan?"Comenzar historia":configured?"Confirmar decisión":"Completa la elección"}</button></footer></article></div>}
  </section>
}

const signed=(value:number,suffix:string)=>value===0?`Sin cambio de${suffix}`:`${value>0?"+":""}${String(value).replace(".",",")}${suffix}`;
const moneyChange=(value:number)=>value===0?"Sin cambio de presupuesto":`${value>0?"+":""}${String(value).replace(".",",")} M`;
function StoryConfiguration({input,squad,value,onChange}:{input:string;squad:Person[];value:Record<string,unknown>;onChange:(value:Record<string,unknown>)=>void}){
 const select=(key:string,label:string,options:Array<{value:string;label:string}>)=><label><span>{label}</span><select value={String(value[key]??"")} onChange={(event)=>onChange({...value,[key]:event.target.value})}><option value="">Elegir…</option>{options.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>;
 const players=squad.map((item)=>({value:item.id,label:`${item.name}${item.original?" · Original":""}`}));
 return <div className="career-story-form">{input==="players"?<>{select("mentor","Veterano o líder",players)}{select("youth","Jugador que recibirá la mentoría",players)}</>:input==="leader"?select("leader","Capitán que representará al vestuario",players):input==="formation"?select("formation","Formación",["4-4-2","4-3-3","3-4-3","3-5-2","5-3-2"].map((v)=>({value:v,label:v}))):input==="scouting"?<>{select("position","Posición",["POR","DEF","MED","DEL"].map((v)=>({value:v,label:v})))}{select("profile","Perfil",[{value:"starter",label:"Titular inmediato"},{value:"potential",label:"Joven con potencial"},{value:"opportunity",label:"Oportunidad de mercado"}])}</>:input==="intensity"?select("intensity","Intensidad",["Baja","Media","Alta"].map((v)=>({value:v,label:v}))):select("tone","Tono",["Ambicioso","Protector","Cercano"].map((v)=>({value:v,label:v})))}</div>
}
