-- Sustituye el metajuego de progreso por capítulos narrativos con decisiones claras.

create or replace function public.manager_career_interlude_story(target_plan text,target_days integer default 18) returns jsonb
language plpgsql immutable set search_path=public as $$
declare story jsonb; d integer:=greatest(4,target_days);
begin
  if target_plan='academy' then story:=jsonb_build_array(
    jsonb_build_object('key','diagnosis','day',1,'label','DIAGNÓSTICO','title','¿Qué necesita la cantera?','description','La dirección deportiva te pide una prioridad clara para este descanso.','input','none','choices',jsonb_build_array(
      jsonb_build_object('key','talent','title','Desarrollar talento','summary','Prioriza el crecimiento individual de los jóvenes.','consequence','La cantera trabajará pensando en el potencial, aunque el resultado inmediato será menor.','reputationChange',2,'confidenceChange',0,'budgetChange',-.15),
      jsonb_build_object('key','identity','title','Reforzar la identidad','summary','Acerca el filial al primer equipo y a sus referentes.','consequence','El club gana identidad, pero exige mantener originales en las próximas alineaciones.','reputationChange',3,'confidenceChange',1,'budgetChange',0),
      jsonb_build_object('key','replacement','title','Preparar relevos','summary','Busca soluciones para posiciones concretas del primer equipo.','consequence','Obtendrás una recomendación deportiva para el mercado.','reputationChange',1,'confidenceChange',0,'budgetChange',-.25))),
    jsonb_build_object('key','mentoring','day',ceil(d*.30),'label','INTERVENCIÓN','title','Elige una pareja de mentoría','description','Un veterano acompañará a un joven durante el resto del descanso.','input','players','choices',jsonb_build_array(
      jsonb_build_object('key','technical','title','Mentoría técnica','summary','Trabajo específico con balón y lectura de juego.','consequence','El joven llegará mejor preparado para competir.','reputationChange',2,'confidenceChange',1,'budgetChange',0),
      jsonb_build_object('key','leadership','title','Mentoría de liderazgo','summary','El veterano transmite hábitos y responsabilidad.','consequence','Mejora la cohesión y la identidad del vestuario.','reputationChange',1,'confidenceChange',3,'budgetChange',0))),
    jsonb_build_object('key','opportunity','day',ceil(d*.60),'label','PRUEBA','title','Ha llegado su oportunidad','description','El cuerpo técnico necesita decidir cómo probar el trabajo realizado.','input','none','choices',jsonb_build_array(
      jsonb_build_object('key','friendly','title','Titular en el amistoso','summary','Una prueba real con exposición y riesgo.','consequence','Si responde, tendrá una ventaja para entrar en el próximo once.','reputationChange',2,'confidenceChange',0,'budgetChange',-.10),
      jsonb_build_object('key','first_team','title','Entrenar con el primer equipo','summary','Integración progresiva sin presión pública.','consequence','La adaptación será más segura, aunque menos visible.','reputationChange',1,'confidenceChange',2,'budgetChange',0),
      jsonb_build_object('key','individual','title','Plan individual','summary','Protege su proceso y trabaja sus debilidades.','consequence','No habrá premio inmediato, pero reduces el riesgo de quemarlo.','reputationChange',0,'confidenceChange',1,'budgetChange',-.20))),
    jsonb_build_object('key','return','day',ceil(d*.82),'label','DECISIÓN FINAL','title','¿Qué lugar tendrá al regresar?','description','La directiva quiere conocer tu decisión antes de abrir la siguiente jornada.','input','none','choices',jsonb_build_array(
      jsonb_build_object('key','lineup','title','Competirá por el once','summary','Le abres la puerta a la titularidad.','consequence','La próxima misión premiará alinear suficientes originales.','reputationChange',4,'confidenceChange',1,'budgetChange',0),
      jsonb_build_object('key','rotation','title','Entrará en la rotación','summary','Minutos progresivos y presión controlada.','consequence','Equilibras identidad y seguridad deportiva.','reputationChange',2,'confidenceChange',2,'budgetChange',0),
      jsonb_build_object('key','loan','title','Preparar una cesión','summary','Priorizas su desarrollo fuera del foco del primer equipo.','consequence','La cantera lo entiende, pero la afición pierde una referencia cercana.','reputationChange',-1,'confidenceChange',1,'budgetChange',.20)))
  );
  elsif target_plan='tactical' then story:=jsonb_build_array(
    jsonb_build_object('key','diagnosis','day',1,'label','DIAGNÓSTICO','title','¿Qué debe cambiar el equipo?','description','El cuerpo técnico revisa la jornada anterior.','input','none','choices',jsonb_build_array(
      jsonb_build_object('key','control','title','Controlar los partidos','summary','Más posesión y menos transiciones.','consequence','Reduce riesgo, pero exige paciencia.','reputationChange',0,'confidenceChange',2,'budgetChange',0),jsonb_build_object('key','pressure','title','Presionar más arriba','summary','Un plan agresivo para recuperar cerca del área.','consequence','Puede dar ventaja deportiva a cambio de desgaste.','reputationChange',1,'confidenceChange',-1,'budgetChange',0),jsonb_build_object('key','vertical','title','Ser más verticales','summary','Atacar rápido y asumir intercambio de golpes.','consequence','La afición lo celebrará, pero aumenta el riesgo.','reputationChange',2,'confidenceChange',-1,'budgetChange',0))),
    jsonb_build_object('key','system','day',ceil(d*.30),'label','INTERVENCIÓN','title','Construye el nuevo sistema','description','Selecciona cómo plasmar la idea en el campo.','input','formation','choices',jsonb_build_array(jsonb_build_object('key','balanced','title','Equilibrio','summary','Un sistema reconocible para todos.','consequence','Ganas seguridad colectiva.','reputationChange',0,'confidenceChange',3,'budgetChange',0),jsonb_build_object('key','specialist','title','Plan específico','summary','Adapta el dibujo al siguiente rival.','consequence','Obtienes protección si falla la próxima misión.','reputationChange',0,'confidenceChange',1,'budgetChange',-.10))),
    jsonb_build_object('key','friendly','day',ceil(d*.60),'label','PRUEBA','title','Ensayo general','description','Decide la intensidad del amistoso.','input','intensity','choices',jsonb_build_array(jsonb_build_object('key','low','title','Intensidad baja','summary','Prioriza salud y conceptos.','consequence','El grupo llega fresco.','reputationChange',0,'confidenceChange',2,'budgetChange',-.10),jsonb_build_object('key','high','title','Intensidad competitiva','summary','Prueba el plan bajo presión real.','consequence','Mayor ventaja potencial, con desgaste.','reputationChange',1,'confidenceChange',-1,'budgetChange',-.15))),
    jsonb_build_object('key','return','day',ceil(d*.82),'label','DECISIÓN FINAL','title','El plan para el regreso','description','Fija la instrucción que llevará el equipo a la próxima jornada.','input','none','choices',jsonb_build_array(jsonb_build_object('key','protect','title','Proteger el resultado','summary','Seguridad antes que espectáculo.','consequence','Reduce una posible pérdida de confianza.','reputationChange',0,'confidenceChange',2,'budgetChange',0),jsonb_build_object('key','attack','title','Salir a dominar','summary','La propuesta más ambiciosa.','consequence','Suma reputación, pero eleva la exigencia.','reputationChange',3,'confidenceChange',-1,'budgetChange',0)))
  );
  elsif target_plan='growth' then story:=jsonb_build_array(
    jsonb_build_object('key','diagnosis','day',1,'label','DIAGNÓSTICO','title','¿Dónde debe crecer el club?','description','El presupuesto es limitado y hay que elegir una vía.','input','none','choices',jsonb_build_array(jsonb_build_object('key','market','title','Preparar un fichaje','summary','Reserva recursos para una posición concreta.','consequence','Ganas información de mercado.','reputationChange',0,'confidenceChange',0,'budgetChange',-.15),jsonb_build_object('key','structure','title','Invertir en estructura','summary','Mejora procesos en lugar de nombres.','consequence','Menos impacto inmediato, más estabilidad.','reputationChange',1,'confidenceChange',2,'budgetChange',-.30),jsonb_build_object('key','commercial','title','Buscar nuevos ingresos','summary','Abre conversaciones con patrocinadores.','consequence','Aumenta el margen, con obligaciones públicas.','reputationChange',0,'confidenceChange',-1,'budgetChange',.50))),
    jsonb_build_object('key','scouting','day',ceil(d*.30),'label','INVESTIGACIÓN','title','Define el encargo de scouting','description','El equipo de captación necesita un perfil.','input','scouting','choices',jsonb_build_array(jsonb_build_object('key','starter','title','Titular inmediato','summary','Coste alto y rendimiento rápido.','consequence','Recibirás una recomendación exigente.','reputationChange',0,'confidenceChange',1,'budgetChange',-.20),jsonb_build_object('key','potential','title','Joven con potencial','summary','Menor impacto y valor futuro.','consequence','Refuerza la visión de largo plazo.','reputationChange',2,'confidenceChange',0,'budgetChange',-.10))),
    jsonb_build_object('key','board','day',ceil(d*.60),'label','NEGOCIACIÓN','title','Reunión con la directiva','description','Puedes pedir apoyo, pero tendrás que aceptar una condición.','input','none','choices',jsonb_build_array(jsonb_build_object('key','budget','title','Pedir presupuesto','summary','Más capacidad para fichar.','consequence','Recibes 0,75 M y aumenta la presión de resultados.','reputationChange',0,'confidenceChange',-2,'budgetChange',.75),jsonb_build_object('key','patience','title','Pedir paciencia','summary','Protege el puesto y renuncia a recursos.','consequence','El consejo te concede margen deportivo.','reputationChange',0,'confidenceChange',4,'budgetChange',0))),
    jsonb_build_object('key','return','day',ceil(d*.82),'label','DECISIÓN FINAL','title','Cierra el plan económico','description','Elige cómo utilizarás lo conseguido.','input','none','choices',jsonb_build_array(jsonb_build_object('key','spend','title','Activar el mercado','summary','El dinero queda disponible para fichar.','consequence','El club espera una mejora visible.','reputationChange',1,'confidenceChange',-1,'budgetChange',.50),jsonb_build_object('key','reserve','title','Crear una reserva','summary','Protege el presupuesto para una crisis futura.','consequence','Ganas estabilidad y confianza.','reputationChange',0,'confidenceChange',3,'budgetChange',0)))
  );
  else story:=jsonb_build_array(
    jsonb_build_object('key','diagnosis','day',1,'label','DIAGNÓSTICO','title',case when target_plan='supporters' then '¿Qué necesita la afición?' else '¿Qué necesita el vestuario?' end,'description','El descanso comienza con una conversación honesta.','input','none','choices',jsonb_build_array(jsonb_build_object('key','listen','title','Escuchar antes de actuar','summary','Reúne información y reduce la tensión.','consequence','Ganas confianza sin prometer resultados.','reputationChange',1,'confidenceChange',3,'budgetChange',0),jsonb_build_object('key','message','title','Enviar un mensaje firme','summary','Marca expectativas desde el primer día.','consequence','Refuerza autoridad, con riesgo de división.','reputationChange',2,'confidenceChange',-1,'budgetChange',0))),
    jsonb_build_object('key','leaders','day',ceil(d*.30),'label','INTERVENCIÓN','title','Apóyate en los líderes','description','Selecciona quién debe sostener el mensaje.','input','players','choices',jsonb_build_array(jsonb_build_object('key','captains','title','Dar voz a los capitanes','summary','Comparte responsabilidad con el vestuario.','consequence','Mejora la cohesión.','reputationChange',0,'confidenceChange',4,'budgetChange',0),jsonb_build_object('key','manager','title','Asumir tú la presión','summary','Proteges al equipo públicamente.','consequence','La afición valora el gesto.','reputationChange',3,'confidenceChange',1,'budgetChange',0))),
    jsonb_build_object('key','public','day',ceil(d*.60),'label','PRUEBA','title','El club vuelve a mostrarse','description','Elige cómo recuperar la conexión exterior.','input','tone','choices',jsonb_build_array(jsonb_build_object('key','open','title','Entrenamiento abierto','summary','Acerca el equipo a su gente.','consequence','Ganas reputación con algo de desgaste.','reputationChange',4,'confidenceChange',-1,'budgetChange',-.10),jsonb_build_object('key','private','title','Proteger al grupo','summary','Trabajo a puerta cerrada.','consequence','La plantilla gana calma.','reputationChange',-1,'confidenceChange',4,'budgetChange',0))),
    jsonb_build_object('key','return','day',ceil(d*.82),'label','DECISIÓN FINAL','title','El mensaje para el regreso','description','Define con qué tono termina el descanso.','input','none','choices',jsonb_build_array(jsonb_build_object('key','ambition','title','Prometer ambición','summary','El equipo vuelve con una meta alta.','consequence','Más reputación y más presión.','reputationChange',4,'confidenceChange',-1,'budgetChange',0),jsonb_build_object('key','unity','title','Hablar de unidad','summary','Reduce ruido y protege el proceso.','consequence','El vestuario regresa más unido.','reputationChange',1,'confidenceChange',4,'budgetChange',0)))
  ); end if;
  return story;
end $$;

-- Laboratorio: añade historia y permite decidir cada capítulo.
do $$ begin if to_regprocedure('public.manager_career_lab_public_preview_v7_base(text)') is null then alter function public.manager_career_lab_public_preview(text) rename to manager_career_lab_public_preview_v7_base; end if; end $$;
create or replace function public.manager_career_lab_public_preview(target_token text) returns jsonb language plpgsql stable security definer set search_path=public as $$
declare result jsonb; active jsonb; story jsonb; chapter jsonb; chosen jsonb; day_no integer;
begin result:=public.manager_career_lab_public_preview_v7_base(target_token); active:=result->'state'->'activeInterlude'; if active is null or active->>'plan' is null then return result; end if;
  day_no:=coalesce((active->>'currentDay')::integer,1); story:=public.manager_career_interlude_story(active->>'plan',coalesce((active->>'activityDays')::integer,18)); chosen:=coalesce(active->'storyChoices','[]'::jsonb);
  select item into chapter from jsonb_array_elements(story) item where (item->>'day')::integer<=day_no and not exists(select 1 from jsonb_array_elements(chosen) c where c->>'chapter'=item->>'key') order by (item->>'day')::integer limit 1;
  active:=active||jsonb_build_object('story',story,'storyChoices',chosen,'currentChapter',chapter,'narrativeMode',true); return jsonb_set(result,'{state,activeInterlude}',active); end $$;

do $$ begin if to_regprocedure('public.manager_career_lab_public_action_v8_base(text,text,jsonb)') is null then alter function public.manager_career_lab_public_action(text,text,jsonb) rename to manager_career_lab_public_action_v8_base; end if; end $$;
create or replace function public.manager_career_lab_public_action(target_token text,target_action text,target_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
<<story_action>> declare selected public.manager_career_lab_sessions%rowtype; state jsonb; active jsonb; story jsonb; chapter jsonb; choice jsonb; chosen jsonb; day_no integer;
begin if target_action<>'interlude_story' then return public.manager_career_lab_public_action_v8_base(target_token,target_action,target_payload); end if;
 select * into selected from public.manager_career_lab_sessions where preview_token=target_token and preview_enabled and status='running' and expires_at>now() for update; if not found then raise exception 'Vista no disponible'; end if;
 state:=selected.state; active:=state->'activeInterlude'; if selected.phase<>'interlude' or active is null or active->>'plan' is null then raise exception 'No hay una historia activa'; end if;
 day_no:=coalesce((active->>'currentDay')::integer,1); story:=public.manager_career_interlude_story(active->>'plan',coalesce((active->>'activityDays')::integer,18)); chosen:=coalesce(active->'storyChoices','[]'::jsonb);
 select item into chapter from jsonb_array_elements(story) item where item->>'key'=target_payload->>'chapter' and (item->>'day')::integer<=day_no and not exists(select 1 from jsonb_array_elements(chosen) c where c->>'chapter'=item->>'key'); if chapter is null then raise exception 'Este capítulo no está disponible'; end if;
 select item into choice from jsonb_array_elements(chapter->'choices') item where item->>'key'=target_payload->>'choice'; if choice is null then raise exception 'Decisión no válida'; end if;
 chosen:=chosen||jsonb_build_array(choice||jsonb_build_object('chapter',chapter->>'key','chapterTitle',chapter->>'title','label',chapter->>'label','configuration',coalesce(target_payload->'configuration','{}'::jsonb),'decidedAt',now(),'day',day_no)); active:=active||jsonb_build_object('storyChoices',chosen); state:=jsonb_set(state,'{activeInterlude}',active);
 update public.manager_career_lab_sessions set state=story_action.state,last_report=jsonb_build_object('action','interlude_story','detail',(chapter->>'title')||': '||(choice->>'title'),'matchday',current_matchday,'phaseBefore','interlude','phaseAfter','interlude','checks',public.manager_career_lab_checks(story_action.state)),updated_at=now() where id=selected.id; return public.manager_career_lab_public_preview(target_token); end $$;

-- Carrera real: persiste elecciones narrativas y las liquida al terminar.
alter table public.manager_career_interlude_programs add column if not exists story_choices jsonb not null default '[]'::jsonb;
do $$ begin if to_regprocedure('public.manager_career_interlude_state_v5_base(uuid)') is null then alter function public.manager_career_interlude_state(uuid) rename to manager_career_interlude_state_v5_base; end if; end $$;
create or replace function public.manager_career_interlude_state(target_career_id uuid) returns jsonb language plpgsql volatile security definer set search_path=public as $$
declare result jsonb; program public.manager_career_interlude_programs%rowtype; story jsonb; chapter jsonb; day_no integer;
begin result:=public.manager_career_interlude_state_v5_base(target_career_id); if result is null or result->>'plan' is null then return result; end if; select * into program from public.manager_career_interlude_programs where career_id=target_career_id and interlude_id=(result->>'id')::uuid;
 day_no:=coalesce((result->>'dayNumber')::integer,1); story:=public.manager_career_interlude_story(program.plan,program.activity_days); select item into chapter from jsonb_array_elements(story) item where (item->>'day')::integer<=day_no and not exists(select 1 from jsonb_array_elements(program.story_choices) c where c->>'chapter'=item->>'key') order by (item->>'day')::integer limit 1;
 return result||jsonb_build_object('story',story,'storyChoices',program.story_choices,'currentChapter',chapter,'narrativeMode',true); end $$;

create or replace function public.save_manager_career_interlude_story(target_career_id uuid,target_interlude_id uuid,target_chapter text,target_choice text,target_configuration jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare career public.manager_careers%rowtype; program public.manager_career_interlude_programs%rowtype; result jsonb; story jsonb; chapter jsonb; choice jsonb; day_no integer;
begin select * into career from public.manager_careers where id=target_career_id and owner_id=auth.uid() and status='active'; if not found then raise exception 'Carrera no disponible'; end if; result:=public.manager_career_interlude_state(career.id); select * into program from public.manager_career_interlude_programs where career_id=career.id and interlude_id=target_interlude_id for update;
 day_no:=coalesce((result->>'dayNumber')::integer,1); story:=public.manager_career_interlude_story(program.plan,program.activity_days); select item into chapter from jsonb_array_elements(story) item where item->>'key'=target_chapter and (item->>'day')::integer<=day_no and not exists(select 1 from jsonb_array_elements(program.story_choices) c where c->>'chapter'=item->>'key'); if chapter is null then raise exception 'Capítulo no disponible'; end if;
 select item into choice from jsonb_array_elements(chapter->'choices') item where item->>'key'=target_choice; if choice is null then raise exception 'Decisión no válida'; end if;
 update public.manager_career_interlude_programs set story_choices=story_choices||jsonb_build_array(choice||jsonb_build_object('chapter',target_chapter,'chapterTitle',chapter->>'title','label',chapter->>'label','configuration',target_configuration,'decidedAt',now(),'day',day_no)),updated_at=now() where id=program.id; return public.manager_career_interlude_state(career.id); end $$;

create or replace function public.settle_manager_career_interlude_program(target_career_id uuid,target_interlude_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare career public.manager_careers%rowtype; program public.manager_career_interlude_programs%rowtype; interlude public.manager_career_interludes%rowtype; rules public.manager_career_rules%rowtype; conf integer; rep integer; budget_delta numeric; result jsonb;
begin select * into career from public.manager_careers where id=target_career_id and owner_id=auth.uid() for update; if not found then raise exception 'Carrera no disponible'; end if; select * into program from public.manager_career_interlude_programs where career_id=career.id and interlude_id=target_interlude_id for update; if not found or program.settled_at is not null then return coalesce(program.reward,'{}'::jsonb); end if;
 select * into interlude from public.manager_career_interludes where id=target_interlude_id; select * into rules from public.manager_career_rules where id; if now()<interlude.ends_at-make_interval(days=>rules.interlude_preparation_days) then raise exception 'El interludio todavía no ha terminado'; end if;
 select coalesce(sum((c->>'confidenceChange')::integer),0),coalesce(sum((c->>'reputationChange')::integer),0),coalesce(sum((c->>'budgetChange')::numeric),0) into conf,rep,budget_delta from jsonb_array_elements(program.story_choices) c;
 result:=jsonb_build_object('tier',case when jsonb_array_length(program.story_choices)>=4 then 'completed' else 'incomplete' end,'title',case when jsonb_array_length(program.story_choices)>=4 then 'Historia completada' else 'Interludio incompleto' end,'description',jsonb_array_length(program.story_choices)||' capítulos decididos.','confidenceChange',conf,'reputationChange',rep,'budgetChange',budget_delta,'chapters',program.story_choices);
 update public.manager_careers set board_confidence=greatest(0,least(100,board_confidence+conf)),reputation=greatest(0,least(100,reputation+rep)),budget=greatest(0,budget+budget_delta),updated_at=now() where id=career.id;
 update public.manager_career_interlude_programs set reward=result,settled_at=now(),updated_at=now() where id=program.id; perform public.create_nexo_notification(career.owner_id,'system','Historia del interludio completada',result->>'description',null,'inicio','career-interlude-story:'||program.id); return result; end $$;

revoke all on function public.manager_career_interlude_story(text,integer) from public; grant execute on function public.manager_career_interlude_story(text,integer) to anon,authenticated,service_role;
revoke all on function public.manager_career_lab_public_preview(text),public.manager_career_lab_public_action(text,text,jsonb) from public; grant execute on function public.manager_career_lab_public_preview(text),public.manager_career_lab_public_action(text,text,jsonb) to anon,authenticated;
revoke all on function public.save_manager_career_interlude_story(uuid,uuid,text,text,jsonb) from public,anon; grant execute on function public.save_manager_career_interlude_story(uuid,uuid,text,text,jsonb) to authenticated;
notify pgrst,'reload schema';
